import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import { ToastProvider } from "~/context/ToastContext";

export const metadata: Metadata = {
  title: "slackご都合以下かですか？",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/icon.png" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <ToastProvider>
        <body>{children}</body>
      </ToastProvider>
    </html>
  );
}
